version: '2.1'

services:
  nodejs:
    build: .
    image: nodejs
    container_name: nodejs
    volumes:
      - "data_work:/home/ubuntu/work"
    #restart: always
    ports:
      - "22:22"
      - "5901:5901"
    network_mode: "host"

volumes:
  data_work:
